name: Publish Docker Images
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
    
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push hoshigakikisame/hris_backend-web_prod image
        id: build-push-web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/production/nginx/Dockerfile
          push: true
          tags: hoshigakikisame/hris_backend-web_prod:latest

      - name: build and push hoshigakikisame/hris_backend-php-fpm_prod image
        id: build-push-php-fpm
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/common/php-fpm/Dockerfile
          push: true
          tags: hoshigakikisame/hris_backend-php-fpm_prod:latest